#!/bin/env bash
# 此脚本欢迎各位脚本作者借鉴,但请勿删除作者标识
# 此脚本作者 ArcticFox Q群 705226976
cd $HOME
black="\e[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
purple="\033[35m"
cyan="\033[36m"
white="\033[37m"
background="\033[0m"
echo
Linux="ubuntu"
Version="jammy"
RootfsName="rootfs.tar.xz"

if [ ! "$(uname -o)" = "Android" ];then
    echo -e ${red}此脚本禁止在Linux中运行${background}
    exit
fi

if ping -c 1 google.com 2>&1 > /dev/null
then
  echo -e ${blue}[${red}*${blue}] ${cyan}错误 ${yellow}请不要开加速器${background}
  exit
fi

case $(uname -m) in
aarch64|arm64)
	Arch="arm64"
	;;
*)
	echo -e ${red}本脚本仅适配 Arm64${background}
	exit
esac

FOLDER="${Linux}-${Version}"
RootfsName="rootfs-${Linux}-${Linux}.tar.xz"

TUNA_URL="https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/${Linux}/${Version}/${Arch}/default/"
BFSU_URL="https://mirrors.bfsu.edu.cn/lxc-images/images/${Linux}/${Version}/${Arch}/default/"
NJU_URL="https://mirror.nju.edu.cn/lxc-images/images/${Linux}/${Version}/${Arch}/default/"

if [ -d $HOME/AF-Proot/${FOLDER} ]
then
  echo -e ${red}您已安装 ${cyan}${FOLDER}${background}
  exit
else
  mkdir -p $HOME/AF-Proot/${FOLDER}
fi

for Download_URL in ${URL[@]}
do
  for Download_Source in ${Site[@]}
  do
    date=$(wget -O index ${Download_URL} | grep -oP '(?<=title=")[^"]+(?=">)' | tail -n 1)
    if wget -O $HOME/AF-Proot/${RootfsName} "${Download_URL}/${date}/rootfs.tar.xz"
    then
      mv -f rootfs.tar.xz $HOME/AF-Proot/${RootfsName}
      break 2
    else
      rm $HOME/AF-Proot/${RootfsName}
      echo -e ${blue}[${yellow}*${blue}] ${red}下载出错${cyan} 更换下载源为 ${purple}${Download_Source}${cyan}${background}
      echo -e ${blue}[${green}*${blue}] ${yellow}重试中.${background}
    fi
  done
done

wget -O $HOME/AF-Proot/${RootfsName} ${}

