#!/bin/bash
cd $(dirname $0)
## pulseaudio --start
## Chroot : pulseaudio --start --system
unset LD_PRELOAD
command="proot"
# command+=" --link2symlink"
command+=" -0"
command+=" -r /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/ubuntu-jammy"
command+=" -b /dev"
command+=" -b /proc"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/ubuntu-jammy/root:/dev/shm"
command+=" -b /sdcard:/sdcard"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/.hushlogin:/root/.hushlogin"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/buddyinfo:/proc/buddyinfo"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/cgroups:/proc/cgroups"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/consoles:/proc/consoles"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/crypto:/proc/crypto"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/devices:/proc/devices"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/diskstats:/proc/diskstats"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/execdomains:/proc/execdomains"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/fb:/proc/fb"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/filesystems:/proc/filesystems"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/interrupts:/proc/interrupts"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/iomem:/proc/iomem"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/ioports:/proc/ioports"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/kallsyms:/proc/kallsyms"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/keys:/proc/keys"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/key-users:/proc/key-users"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/kpageflags:/proc/kpageflags"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/loadavg:/proc/loadavg"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/locks:/proc/locks"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/misc:/proc/misc"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/modules:/proc/modules"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/pagetypeinfo:/proc/pagetypeinfo"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/partitions:/proc/partitions"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/sched_debug:/proc/sched_debug"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/softirqs:/proc/softirqs"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/timer_list:/proc/timer_list"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/uptime:/proc/uptime"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/version:/proc/version"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/vmallocinfo:/proc/vmallocinfo"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/vmstat:/proc/vmstat"
command+=" -b /data/user/0/bin.mt.plus.canary/files/term/home/AF-Proot/proc/zoneinfo:/proc/zoneinfo"
command+=" -w /root"
command+=" /usr/bin/env -i"
command+=" HOME=/root"
command+=" PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/games:/usr/local/games"
command+=" TERM=$TERM"
command+=" LANG=zh_CN.UTF-8"
command+=" /bin/bash --login"
com="$@"
if [ -z "$1" ];then
    exec $command
else
    $command -c "$com"
fi
