#!/bin/env bash
source ../config
if [ -e /usr/share/fonts/lxgw-wenkai/LXGWWenKaiScreen.ttf ]
then
  exit 0
fi
FontsURL="https://github.com/lxgw/LxgwWenKai-Screen/releases/download/v1.330/LXGWWenKaiScreen.ttf"
if CheckNetwork
then
  GithubMirror=("https://gitdl.cn/" "https://mirror.ghproxy.com/" "https://gh.arcticfox.top/")
else
  GithubMirror=(" ")
fi
echo -e ${green}正在安装 ${yellow}中文字体${background}
for i in ${GithubMirror[@]}
do
  Fonts_URL="${i}${FontsURL}"
  if Download LXGWWenKaiScreen.ttf ${Fonts_URL}
  then
    break
  fi
done
if [ ! -d /usr/share/fonts/lxgw-wenkai ]
then
  mkdir -p /usr/share/fonts/lxgw-wenkai
fi
mv -vf LXGWWenKaiScreen.ttf /usr/share/fonts/lxgw-wenkai/LXGWWenKaiScreen.ttf
echo -e ${yellow}正在加载字体${background}
fc-cache -f
echo -e ${yellow}完成${background}