#!/bin/env bash
source ../config
cd $HOME

echo -e ${yellow}正在修改 ${cyan}DNS配置${background}
rm /etc/resolv.conf
echo 'nameserver 223.5.5.5
nameserver 223.6.6.6
nameserver 2400:3200::1
nameserver 2400:3200:baba::1' > /etc/resolv.conf
cat /etc/resolv.conf
echo -e ${yellow}已修改为 ${cyan}阿里DNS${background}

echo -e ${yellow}正在修改 ${cyan}Pacman仓库源${background}
echo '
##
## MSYS2 repository mirrorlist
##

## Primary
## msys2.org
Server = https://mirrors.bfsu.edu.cn/msys2/msys/$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/$arch
Server = https://mirror.nju.edu.cn/msys2/msys/$arch
Server = https://mirrors.aliyun.com/msys2/msys/$arch
' > mirrorlist.msys

cat > mirrorlist.mingw64 <<- FOX
##
## 32-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = https://mirrors.bfsu.edu.cn/msys2/msys/x86_64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64
Server = https://mirror.nju.edu.cn/msys2/msys/x86_64
Server = https://mirrors.aliyun.com/msys2/msys/x86_64
FOX

cat > mirrorlist.mingw32 <<- FOX
##
## 32-bit Mingw-w64 repository mirrorlist
##

## Primary
## msys2.org
Server = https://mirrors.bfsu.edu.cn/msys2/msys/i686
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/i686
Server = https://mirror.nju.edu.cn/msys2/msys/i686
Server = https://mirrors.aliyun.com/msys2/msys/i686
FOX

cat > mirrorlist.clang64 <<- FOX
## Primary
Server = https://mirrors.bfsu.edu.cn/msys2/mingw/clang64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/clang64
Server = https://mirror.nju.edu.cn/msys2/mingw/clang64
Server = https://mirrors.aliyun.com/msys2/mingw/clang64
FOX

cat > mirrorlist.clang32 <<- FOX
## Primary
Server = https://mirrors.bfsu.edu.cn/msys2/mingw/clang32
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/clang32
Server = https://mirror.nju.edu.cn/msys2/mingw/clang32
Server = https://mirrors.aliyun.com/msys2/mingw/clang32
FOX

cat > mirrorlist.ucrt64 <<- FOX
## Primary
Server = https://mirrors.bfsu.edu.cn/msys2/mingw/ucrt64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/ucrt64
Server = https://mirror.nju.edu.cn/msys2/mingw/ucrt64
Server = https://mirrors.aliyun.com/msys2/mingw/ucrt64
FOX

mv -f mirrorlist.msys /etc/pacman.d/mirrorlist.msys
mv -f mirrorlist.mingw64 /etc/pacman.d/mirrorlist.mingw64
mv -f mirrorlist.mingw32 /etc/pacman.d/mirrorlist.mingw32
mv -f mirrorlist.clang64 /etc/pacman.d/mirrorlist.clang64
mv -f mirrorlist.clang32 /etc/pacman.d/mirrorlist.clang32
mv -f mirrorlist.ucrt64 /etc/pacman.d/mirrorlist.ucrt64
cat /etc/pacman.d/mirrorlist.msys
echo -e ${yellow}修改完成${background}

echo -e ${yellow}正在更新 ${cyan}MSYS2${background}
if pacman -Syyu --noconfirm --needed
then
  echo -e ${yellow}更新完成${background}
else
  ErrorReturn
fi

echo -e ${yellow}正在安装 ${cyan}依赖软件${background}
if pacman -S --needed --noconfirm docker-ce
then
  echo -e ${cyan}安装完成${background}
else
  ErrorReturn
fi