#!/bin/env bash
source ../config
if $(node -v > /dev/null 2>&1)
then
  NodeVersion=$(node -v)
  NodeVersion=${NodeVersion:1:2}
  if [ ${NodeVersion} -gt 18 ] || [ ${NodeVersion} -eq 18 ]
  then
    exit 0
  else
    apt -y autoremove nodejs
  fi
fi

if CheckNetwork
then
  NodeVersionURL="https://registry.npmmirror.com/-/binary/node/latest-iron/"
  echo -e ${yellow}正在获取 ${cyan}NodeJS版本号${background}
  until NodeVersion="$(curl -L ${NodeVersionURL} | jq . | grep .pkg | awk -F 'node-|\.pkg' '{print $2}' | sort -V | tail -n 1)"
  do
    echo -e ${cyan}获取失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
else
  NodeVersionURL="https://nodejs.org/dist/latest-iron/"
  echo -e ${yellow}正在获取 ${cyan}NodeJS版本号${background}
  until NodeVersion="$(curl -L ${NodeVersionURL} | grep .pkg | awk -F 'node-|\.pkg' '{print $2}' | tail -n 1)"
  do
    echo -e ${cyan}获取失败 ${yellow}三秒后重试${background}
    sleep 3s
  done
fi

if CheckNetwork
then
  NodeJSURL="https://registry.npmmirror.com/-/binary/node/latest-iron/node-${NodeVersion}-linux-$(Arch).tar.xz"
else
  NodeJSURL="https://nodejs.org/dist/latest-iron/node-${NodeVersion}-linux-$(Arch).tar.xz"
fi

Download NodeJS.tar.xz ${NodeJSURL}

mkdir NodeJS
if ! pv NodeJS.tar.xz | tar -Jxf - -C NodeJS
then
  echo -e ${red}解压失败${background}
  ErrorReturn
fi
rm -rvf NodeJS.tar.xz
rm -rf /usr/local/NodeJS > /dev/null 2>&1
mv NodeJS/$(ls NodeJS) /usr/local/NodeJS
rm -rf NodeJS
echo '
#Node.JS
export PATH=$PATH:/usr/local/NodeJS/bin
' >> /etc/profile
export PATH=$PATH:/usr/local/NodeJS/bin
if ! $(node -v > /dev/null 2>&1)
then
  ErrorReturn
fi
