#!/bin/env bash
if [ -e $AFYZHOME/config ]
then
  source $AFYZHOME/config
fi
CheckInstall $1
case $1 in
YN|Yunzai-Next)
  BotName="Yunzai-Next"
  COMMAND="YZ-NEXT"
  StartCommand="node src/main"
  Pm2Name="yunzai-next"
  ;;
MZ|Miao-Yunzai)
  BotName="Miao-Yunzai"
  COMMAND="Miao-Yun"
  StartCommand="node app"
  Pm2Name="Miao-Yunzai"
  ;;
TZ|TRSS-Yunzai)
  BotName="TRSS-Yunzai"
  COMMAND="TRSS Yunzai"
  StartCommand="node app"
  Pm2Name="TRSS-Yunzai"
  ;;
up)
  echo -e ${yellow} - ${cyan}开始更新${background}
  cd $AFYZHOME
  if CheckNetwork
  then
    if ! grep -q ghproxy .git/config
    then
      git remote add ghproxy https://mirror.ghproxy.com/https://github.com/ArcticFox520/Yunzai-Script.git
    fi
    remote=ghproxy
  else
    remote=origin
  fi
  git fetch ${remote}
  git reset --hard ${remote}/main
  if git pull ${remote} main --force
  then
    echo -e ${yellow} - ${cyan}更新成功${background}
    echo -e ${yellow} - ${cyan}请使用 ${green}afyz ${cyan}命令 打开脚本${background}
  else
    echo -e ${red}更新失败${background}
  fi
  ;;
esac
case $2 in
start)
  START "${StartCommand}" ${Pm2Name}
  ;;
stop)
  StopBot ${BotName} ${COMMAND} ${Pm2Name}
  ;;
restart)
  RestartBot ${BotName} ${COMMAND} ${Pm2Name}
  ;;
log)
  LogBot ${BotName} ${COMMAND} ${Pm2Name}
  ;;
SignApi)
  ConfigFile="config/config/bot.yaml"
  if [ ! -e ${ConfigFile} ]
  then
    echo -e ${red}错误 ${cyan}文件不存在${background}
    exit
  fi
  NewSignApiAddr="$3"
  OldSignApiAddr="$(grep sign_api_addr ${ConfigFile})"
  OldSignApiAddr="$(grep sign_api_addr ${ConfigFile})"
  NewSignApiAddr=$(echo ${NewSignApiAddr} | sed "s|sign_api_addr: ||g")
  sed -i "s|${OldSignApiAddr}|sign_api_addr: ${NewSignApiAddr}|g" ${ConfigFile}
  API=$(grep sign_api_addr ${ConfigFile} | sed "s|sign_api_addr: ||g")
  echo -e ${green}签名API已经修改为 ${cyan}${API}${background}
  ;;
esac