#!/bin/env bash
if [ -e $AFHOME/config ]
then
  source $AFHOME/config
fi
CheckInstall $1
case $1 in
YN|Yunzai-Next)
  BotName="Yunzai-Next"
  COMMAND="YZ-NEXT"
  StartCommand="node src/main"
  Pm2Name="yunzai-next"
  ;;
MZ|Miao-Yunzai)
  BotName="Miao-Yunzai"
  COMMAND="Miao-Yun"
  StartCommand="node app"
  Pm2Name="Miao-Yunzai"
  ;;
TZ|TRSS-Yunzai)
  BotName="TRSS-Yunzai"
  COMMAND="TRSS Yunzai"
  StartCommand="node app"
  Pm2Name="TRSS-Yunzai"
  ;;
up)
  echo -e ${yellow} - ${cyan}开始更新${background}
  cd $AFHOME
  if CheckNetwork
  then
    if ! grep -q ghproxy .git/config
    then
      git remote add gitclone https://mirror.ghproxy.com/https://github.com/ArcticFox520/Yunzai-Script.git
    fi
    remote=ghproxy
  else
    remote=origin
  fi
  git fetch ${remote}
  git reset --hard ${remote}/main
  if git pull ${remote} main --force
  then
    echo -e ${yellow} - ${cyan}更新成功${background}
    echo -e ${yellow} - ${cyan}请使用 ${green}afyz ${cyan}命令 打开脚本${background}
  else
    echo -e ${red}更新失败${background}
  fi
  ;;
esac
case $2 in
start)
  START "${StartCommand}" ${Pm2Name}
  ;;
stop)
  StopBot ${BotName} ${COMMAND} ${Pm2Name}
  ;;
restart)
  RestartBot ${BotName} ${COMMAND} ${Pm2Name}
  ;;
log)
  LogBot ${BotName} ${COMMAND} ${Pm2Name}
  ;;
esac