#!/bin/env bash
source $AFYZHOME/config
TitleText=$1
function CheckFile(){
if [ ! -e $1 ]
then
  $(TUISoftware) --title "${TitleText}" \
  --msgbox "文件不存在" \
  $(MsgboxSize)
  exit
fi
}

Number=$($(TUISoftware) \
--title "${TitleText}" \
--menu "$(MenuTips)" \
$(MenuSize) \
"1" "修改账号" \
"2" "修改签名" \
"3" "修改主人" \
"4" "全量备份" \
"0" "  返回  " \
3>&1 1>&2 2>&3)
case ${Number} in
1)
  case $(jq .name package.json) in
  "trss-yunzai")
    $(TUISoftware) --title "${TitleText}" \
    --msgbox "TRSS-Yunzai 暂无法修改" \
    $(MsgboxSize)
    exit
    ;;
  esac
  ConfigFile="config/config/qq.yaml"
  CheckFile ${ConfigFile}
  OldQQ="$(grep qq: ${ConfigFile})"
  OldPwd="$(grep pwd: ${ConfigFile})"
  OldPlatform="$(grep platform: ${ConfigFile})"
  if ! NewQQ=$($(TUISoftware) --title "${TitleText}" \
  --yes-button "确认" \
  --no-button "返回" \
  --inputbox "请输入您的QQ账号" \
  $(MsgboxSize) \
  3>&1 1>&2 2>&3)
  then
    exit 0
  fi
  if ! OldPwd=$($(TUISoftware) --title "${TitleText}" \
  --yes-button "确认" \
  --no-button "返回" \
  --inputbox "请输入您的QQ密码" \
  $(MsgboxSize) \
  3>&1 1>&2 2>&3)
  then
    exit 0
  fi
  NewPlatform=$($(TUISoftware) \
  --title "${TitleText}" \
  --menu "$(MenuTips)" \
  $(MenuSize) \
  "1" "安卓手机" \
  "2" "aPad" \
  "3" "安卓手表" \
  "4" "MacOS" \
  "5" "iPad" \
  "6" "Tim" \
  3>&1 1>&2 2>&3)
  if $(TUISoftware) --title "${TitleText}" \
  --yes-button "确认" \
  --no-button "返回" \
  --inputbox "QQ: ${NewQQ}\n密码: ${OldPwd}" \
  $(MsgboxSize)
  then
    sed -i "s|${OldQQ}|qq: ${NewQQ}|g" ${ConfigFile}
    sed -i "s|${OldPwd}|pwd: ${OldPwd}|g" ${ConfigFile}
    sed -i "s|${OldPlatform}|platform: ${NewPlatform}|g" ${ConfigFile}
  else
    exit 0
  fi
;;
2)
  case $(jq .name package.json) in
  "trss-yunzai")
    $(TUISoftware) --title "${TitleText}" \
    --msgbox "TRSS-Yunzai 暂无法修改" \
    $(MsgboxSize)
    exit
    ;;
  esac
  ConfigFile="config/config/bot.yaml"
  CheckFile ${ConfigFile}
  if NewSignApiAddr=$($(TUISoftware) --title "${TitleText}" \
  --yes-button "确认" \
  --no-button "返回" \
  --inputbox "请输入您的签名服务器链接" \
  $(MsgboxSize) \
  3>&1 1>&2 2>&3)
  then
    OldSignApiAddr="$(grep sign_api_addr ${ConfigFile})"
    OldSignApiAddr="$(grep sign_api_addr ${ConfigFile})"
    NewSignApiAddr=$(echo ${NewSignApiAddr} | sed "s|sign_api_addr: ||g")
    sed -i "s|${OldSignApiAddr}|sign_api_addr: ${NewSignApiAddr}|g" ${ConfigFile}
    API=$(grep sign_api_addr ${ConfigFile} | sed "s|sign_api_addr: ||g")
    $(TUISoftware) --title "${TitleText}" \
    --msgbox "签名API已修改为\n${API}" \
    $(MsgboxSize)
  else
    exit
  fi
;;
3)
  ConfigFile="config/config/other.yaml"
  CheckFile ${ConfigFile}
  if MasterQQ=$($(TUISoftware) --title "${TitleText}" \
  --yes-button "确认" \
  --no-button "返回" \
  --inputbox "请输入您的主人账号" \
  $(MsgboxSize) \
  3>&1 1>&2 2>&3)
  then
    if echo ${MasterQQ} | grep -qE '^[0-9]+$'
    then
      sed -i "/masterQQ/a\  - ${MasterQQ}" ${ConfigFile}
    else
      MasterQQ=\"${MasterQQ}\"
      sed -i "/masterQQ/a\  - ${MasterQQ}" ${ConfigFile}
    fi
  else
    exit 0
  fi
;;
4)
  unset Exclude i Options
  BotFOLDER=$(basename $(pwd))
  if [ -d /mnt/c ]
  then
    for i in $(ls /mnt)
    do
      Options="${Options} ${i} 🍥"
    done
    FOLDER=$($(TUISoftware) \
    --title "${TitleText}" \
    --menu "请问您要将备份文件放置于哪里?" \
    $(MenuSize) \
    ${Options} \
    3>&1 1>&2 2>&3)
    FilePath="/mnt/${FOLDER}/${BotFOLDER}"
  else
    if [ -d /sdcard/Download ]
    then
      FilePath="/sdcard/Download/${BotFOLDER}"
    else
      FilePath="./${BotFOLDER}"
    fi
  fi
  echo -e ${yellow}正在执行 ${green}git gc${background}
  git gc
  for i in $(ls plugins)
  do
    if [ -d plugins/${i}/.git ];then
      cd plugins/${i}
      git gc
      cd ../..
    fi
  done
  echo -e ${yellow}执行完成${background}
  echo -e ${yellow}正在统计 ${green}文件排除项${background}
  for i in $(ls plugins)
  do
    if [ -d plugins/${i}/node_modules ];then
      Exclude="${Exclude} --exclude=plugins/${i}/node_modules"
    fi
  done
  cd ..
  Exclude="${Exclude} --exclude=${BotFOLDER}/node_modules"
  echo -e ${yellow}统计完成${background}
  if ($(TUISoftware) --title "${TitleText}"  \
  --yes-button "仅归档" \
  --no-button "压缩" \
  --yesno "是否压缩${BotFOLDER} \n这可能会带来额外的时间消耗" \
  $(MsgboxSize))
  then
    tar -cf - ${Exclude} ${BotFOLDER} | pv > ${FilePath}.tar
  else  
    tar -cf - ${Exclude} ${BotFOLDER} | pv | xz > ${FilePath}.tar.xz
  fi
  echo -e ${green}文件已备份至${FilePath} ${cyan}回车返回${background};read
;;
0)
exit
;;
esac